<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1903d7550adeb4bddbf030e1c5c490ab
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Picqer\\Barcode\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Picqer\\Barcode\\' => 
        array (
            0 => __DIR__ . '/..',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1903d7550adeb4bddbf030e1c5c490ab::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1903d7550adeb4bddbf030e1c5c490ab::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
